[package]
name = "decon"
version = "0.1.0"
authors = ["Shiwei Zhang <ylxdzsw@gmail.com>"]
edition = "2021"

[dependencies]
decon-macro-impl = { path = "./macro-impl" }

# Rust doesn't allow export anything else in a proc_macro crate.
[workspace]
