[package]
name = "decon"
version = "0.1.0"
authors = ["Shiwei Zhang <ylxdzsw@gmail.com>"]
edition = "2021"

[dependencies]
decon-macro-impl = { path = "./macro-impl" }
dyn-clone = "1.0"

# Rust refuses to export anything not a proc_macro in a proc_macro crate.
[workspace]